### ISSUE TITLE
大神您好，升级1.0.9后，书架收集的书全部消失了，并且无法保存书籍到书架，望修复

### ISSUE THREAD

**Issue by ashenone523811** [hongchacha/cartoon#39]
。。。

**Comment by ashenone523811** [comment]
手机黑鲨3s 基于miui12.5

**Comment by MWTJC** [comment]
,手持红米K30s，一样的问题，最后破釜沉舟正常卸载重装最新版，书架就回来了

**Comment by MWTJC** [comment]
> 手机黑鲨3s 基于miui12.5
,手持红米K30s，一样的问题，最后破釜沉舟正常卸载重装最新版，书架就回来了

**Comment by MWTJC** [comment]
> 手机黑鲨3s 基于miui12.5

,手持红米K30s，一样的问题，最后破釜沉舟正常卸载重装最新版，书架就回来了（估计相关文件存在手机用户存储里，别去清理卸载残留啥的）

**Comment by fghtrt** [comment]
>给这个这个软件储存权限应该能解决。手机是红米k30 系统12.5。或者重新删了重新下载，下载好打开点击始终允许也可以

**Comment by fghtrt** [comment]
希望对你有用

**Comment by hongchacha** [comment]
> > 手机黑鲨3s 基于miui12.5
> 
> ,手持红米K30s，一样的问题，最后破釜沉舟正常卸载重装最新版，书架就回来了（估计相关文件存在手机用户存储里，别去清理卸载残留啥的）

確實有BUG，但不用重裝，徹底退出APP，重新開就可以了
