### ISSUE TITLE
爱看韩漫网址已经更改了

### ISSUE THREAD

**Issue by silent-root** [hongchacha/cartoon#53]
![IMG_20240125_154913](https://github.com/hongchacha/cartoon/assets/76520044/9eb5bba7-a4d4-4152-98a8-19c9f5b961cd)

**Comment by hayabusa1997** [comment]
这个网址被一个垃圾网站用掉了，导致书签啥的全乱了。
爱看韩漫真正的网址变成了
https://www.aikanhanman.com/
希望有好心的大佬能做一下json啥的

**Comment by hayabusa1997** [comment]
大佬你是怎么解决的？

**Comment by silent-root** [comment]
因为他自动恢复了，只不过有的漫画和名字对不上
![Uploading Screenshot_20240130_112254.jpg…]()

**Comment by silent-root** [comment]
因为他自动恢复了，只是有的漫画和名字对不上
![Uploading Screenshot_20240130_112254.jpg…]()

**Comment by silent-root** [comment]
> 大佬你是怎么解决的？

我换了个版本的可以了，就那个其他版本里面的中文特别版

**Comment by wyun96711256** [comment]
这个网站今天又崩溃了
